# Generated by Django 5.2.16 on 2026-10-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_rename_50k_no_attitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointset',
            name='body',
            field=models.CharField(choices=[('earth', '지구'), ('moon', '달'), ('mars', '화성'), ('mercury', '수성')], db_index=True, default='earth', max_length=10, verbose_name='몸'),
        ),
        migrations.AlterField(
            model_name='pointsetdeletion',
            name='body',
            field=models.CharField(choices=[('earth', '지구'), ('moon', '달'), ('mars', '화성'), ('mercury', '수성')], default='earth', max_length=10, verbose_name='몸'),
        ),
    ]
